//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Sci.Nlayer.Dominio.ModuloPrincipal.Entidades
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(RolPropiedad))]
    [KnownType(typeof(ValorPropiedad))]
    public partial class Propiedad: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int PropiedadId
        {
            get { return _propiedadId; }
            set
            {
                if (_propiedadId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PropiedadId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _propiedadId = value;
                    OnPropertyChanged("PropiedadId");
                }
            }
        }
        private int _propiedadId;
    
        [DataMember]
        public string Nombre
        {
            get { return _nombre; }
            set
            {
                if (_nombre != value)
                {
                    _nombre = value;
                    OnPropertyChanged("Nombre");
                }
            }
        }
        private string _nombre;
    
        [DataMember]
        public string Tipo
        {
            get { return _tipo; }
            set
            {
                if (_tipo != value)
                {
                    _tipo = value;
                    OnPropertyChanged("Tipo");
                }
            }
        }
        private string _tipo;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<RolPropiedad> RolPropiedad
        {
            get
            {
                if (_rolPropiedad == null)
                {
                    _rolPropiedad = new TrackableCollection<RolPropiedad>();
                    _rolPropiedad.CollectionChanged += FixupRolPropiedad;
                }
                return _rolPropiedad;
            }
            set
            {
                if (!ReferenceEquals(_rolPropiedad, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_rolPropiedad != null)
                    {
                        _rolPropiedad.CollectionChanged -= FixupRolPropiedad;
                    }
                    _rolPropiedad = value;
                    if (_rolPropiedad != null)
                    {
                        _rolPropiedad.CollectionChanged += FixupRolPropiedad;
                    }
                    OnNavigationPropertyChanged("RolPropiedad");
                }
            }
        }
        private TrackableCollection<RolPropiedad> _rolPropiedad;
    
        [DataMember]
        public TrackableCollection<ValorPropiedad> ValorPropiedad
        {
            get
            {
                if (_valorPropiedad == null)
                {
                    _valorPropiedad = new TrackableCollection<ValorPropiedad>();
                    _valorPropiedad.CollectionChanged += FixupValorPropiedad;
                }
                return _valorPropiedad;
            }
            set
            {
                if (!ReferenceEquals(_valorPropiedad, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_valorPropiedad != null)
                    {
                        _valorPropiedad.CollectionChanged -= FixupValorPropiedad;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (ValorPropiedad item in _valorPropiedad)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _valorPropiedad = value;
                    if (_valorPropiedad != null)
                    {
                        _valorPropiedad.CollectionChanged += FixupValorPropiedad;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (ValorPropiedad item in _valorPropiedad)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("ValorPropiedad");
                }
            }
        }
        private TrackableCollection<ValorPropiedad> _valorPropiedad;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            RolPropiedad.Clear();
            ValorPropiedad.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupRolPropiedad(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (RolPropiedad item in e.NewItems)
                {
                    item.Propiedad = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("RolPropiedad", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (RolPropiedad item in e.OldItems)
                {
                    if (ReferenceEquals(item.Propiedad, this))
                    {
                        item.Propiedad = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("RolPropiedad", item);
                    }
                }
            }
        }
    
        private void FixupValorPropiedad(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (ValorPropiedad item in e.NewItems)
                {
                    item.Propiedad = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("ValorPropiedad", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ValorPropiedad item in e.OldItems)
                {
                    if (ReferenceEquals(item.Propiedad, this))
                    {
                        item.Propiedad = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("ValorPropiedad", item);
                        // Delete the dependent end of this identifying association. If the current state is Added,
                        // allow the relationship to be changed without causing the dependent to be deleted.
                        if (item.ChangeTracker.State != ObjectState.Added)
                        {
                            item.MarkAsDeleted();
                        }
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }

        #endregion
    }
}
