//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Nlayer.Nlayer.Dominio.ModuloPrincipal.Entidades
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Rol))]
    [KnownType(typeof(Usuario))]
    public partial class RolUsuario: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int RolUsuarioId
        {
            get { return _rolUsuarioId; }
            set
            {
                if (_rolUsuarioId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'RolUsuarioId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _rolUsuarioId = value;
                    OnPropertyChanged("RolUsuarioId");
                }
            }
        }
        private int _rolUsuarioId;
    
        [DataMember]
        public int UsuarioId
        {
            get { return _usuarioId; }
            set
            {
                if (_usuarioId != value)
                {
                    ChangeTracker.RecordOriginalValue("UsuarioId", _usuarioId);
                    if (!IsDeserializing)
                    {
                        if (Usuario != null && Usuario.UsuarioId != value)
                        {
                            Usuario = null;
                        }
                    }
                    _usuarioId = value;
                    OnPropertyChanged("UsuarioId");
                }
            }
        }
        private int _usuarioId;
    
        [DataMember]
        public int RolId
        {
            get { return _rolId; }
            set
            {
                if (_rolId != value)
                {
                    ChangeTracker.RecordOriginalValue("RolId", _rolId);
                    if (!IsDeserializing)
                    {
                        if (Rol != null && Rol.RolId != value)
                        {
                            Rol = null;
                        }
                    }
                    _rolId = value;
                    OnPropertyChanged("RolId");
                }
            }
        }
        private int _rolId;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Rol Rol
        {
            get { return _rol; }
            set
            {
                if (!ReferenceEquals(_rol, value))
                {
                    var previousValue = _rol;
                    _rol = value;
                    FixupRol(previousValue);
                    OnNavigationPropertyChanged("Rol");
                }
            }
        }
        private Rol _rol;
    
        [DataMember]
        public Usuario Usuario
        {
            get { return _usuario; }
            set
            {
                if (!ReferenceEquals(_usuario, value))
                {
                    var previousValue = _usuario;
                    _usuario = value;
                    FixupUsuario(previousValue);
                    OnNavigationPropertyChanged("Usuario");
                }
            }
        }
        private Usuario _usuario;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Rol = null;
            Usuario = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupRol(Rol previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.RolUsuario.Contains(this))
            {
                previousValue.RolUsuario.Remove(this);
            }
    
            if (Rol != null)
            {
                if (!Rol.RolUsuario.Contains(this))
                {
                    Rol.RolUsuario.Add(this);
                }
    
                RolId = Rol.RolId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Rol")
                    && (ChangeTracker.OriginalValues["Rol"] == Rol))
                {
                    ChangeTracker.OriginalValues.Remove("Rol");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Rol", previousValue);
                }
                if (Rol != null && !Rol.ChangeTracker.ChangeTrackingEnabled)
                {
                    Rol.StartTracking();
                }
            }
        }
    
        private void FixupUsuario(Usuario previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.RolUsuario.Contains(this))
            {
                previousValue.RolUsuario.Remove(this);
            }
    
            if (Usuario != null)
            {
                if (!Usuario.RolUsuario.Contains(this))
                {
                    Usuario.RolUsuario.Add(this);
                }
    
                UsuarioId = Usuario.UsuarioId;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Usuario")
                    && (ChangeTracker.OriginalValues["Usuario"] == Usuario))
                {
                    ChangeTracker.OriginalValues.Remove("Usuario");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Usuario", previousValue);
                }
                if (Usuario != null && !Usuario.ChangeTracker.ChangeTrackingEnabled)
                {
                    Usuario.StartTracking();
                }
            }
        }

        #endregion

    }
}
