//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nlayer.Nlayer.Infraestructura.Datos.Nucleo.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nlayer.Nlayer.Infraestructura.Datos.Nucleo.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Contenedor no puede ser ..
        /// </summary>
        internal static string ContenedorNulo {
            get {
                return ResourceManager.GetString("ContenedorNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Entidad no puede Ser [NULL]..
        /// </summary>
        internal static string EntidadNula {
            get {
                return ResourceManager.GetString("EntidadNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Manejador de Trazas no puede ser [NULL]..
        /// </summary>
        internal static string ManejadorDeTrazasNulo {
            get {
                return ResourceManager.GetString("ManejadorDeTrazasNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha llamado el médoto: Agregar, en un repositorio de tipo: {0}..
        /// </summary>
        internal static string TrazaRepositorioAgregar {
            get {
                return ResourceManager.GetString("TrazaRepositorioAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha creado un repositorio de tipo: {0}..
        /// </summary>
        internal static string TrazaRepositorioCreado {
            get {
                return ResourceManager.GetString("TrazaRepositorioCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha llamado el método: Modificar, en un repositorio de tipo {0}..
        /// </summary>
        internal static string TrazaRepositorioModificar {
            get {
                return ResourceManager.GetString("TrazaRepositorioModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha llamado el método: Obtener, en un repositorio de tipo {0}..
        /// </summary>
        internal static string TrazaRepositorioObtener {
            get {
                return ResourceManager.GetString("TrazaRepositorioObtener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha llamado el método: ObtenerPorFiltro, en un repositorio de tipo {0}, con el filtro: {1}..
        /// </summary>
        internal static string TrazaRepositorioObtenerPorFiltro {
            get {
                return ResourceManager.GetString("TrazaRepositorioObtenerPorFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha llamado el método: Registrar, en un repositorio de tipo {0}..
        /// </summary>
        internal static string TrazaRepositorioRegistrar {
            get {
                return ResourceManager.GetString("TrazaRepositorioRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha llamado el método: Remover, en un repositorio de tipo {0}.
        /// </summary>
        internal static string TrazaRepositorioRemover {
            get {
                return ResourceManager.GetString("TrazaRepositorioRemover", resourceCulture);
            }
        }
    }
}
