//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sci.Nlayer.Presentacion.AgenteDeServicios.Proxies.ServicioDistribuido {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorServicio", Namespace="http://schemas.datacontract.org/2004/07/Sci.Nlayer.ServiciosDistribuidos.Nucleo.M" +
        "anejoDeErrores")]
    [System.SerializableAttribute()]
    public partial class ErrorServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeDeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeDeError {
            get {
                return this.MensajeDeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeDeErrorField, value) != true)) {
                    this.MensajeDeErrorField = value;
                    this.RaisePropertyChanged("MensajeDeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxies.ServicioDistribuido.IServicioDistribuido")]
    public interface IServicioDistribuido {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDistribuido/Test", ReplyAction="http://tempuri.org/IServicioDistribuido/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sci.Nlayer.Presentacion.AgenteDeServicios.Proxies.ServicioDistribuido.ErrorServicio), Action="http://tempuri.org/IServicioDistribuido/TestErrorServicioFault", Name="ErrorServicio", Namespace="http://schemas.datacontract.org/2004/07/Sci.Nlayer.ServiciosDistribuidos.Nucleo.M" +
            "anejoDeErrores")]
        bool Test();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioDistribuidoChannel : Sci.Nlayer.Presentacion.AgenteDeServicios.Proxies.ServicioDistribuido.IServicioDistribuido, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDistribuidoClient : System.ServiceModel.ClientBase<Sci.Nlayer.Presentacion.AgenteDeServicios.Proxies.ServicioDistribuido.IServicioDistribuido>, Sci.Nlayer.Presentacion.AgenteDeServicios.Proxies.ServicioDistribuido.IServicioDistribuido {
        
        public ServicioDistribuidoClient() {
        }
        
        public ServicioDistribuidoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioDistribuidoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDistribuidoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDistribuidoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Test() {
            return base.Channel.Test();
        }
    }
}
